export const keywords = [
    // 🧑 個人名稱/暱稱
    "FanYu",
    "范余",
    "飯魚",
    "Fan-Yu Zhen-Fu",
    "范余振富",
    "飯魚正負",
    "fan._.yuu",
    "fan._.yuuu",
    "fanyuuu2006",
    "范振富",
    "z04m65p4zj4",
    "@fanyuuu2006",

    // 💻 技能與職能 - 擴展更多相關詞彙
    "Frontend Developer",
    "Web Developer",
    "Fullstack Developer",
    "Full Stack Developer",
    "前端工程師",
    "網頁開發者",
    "全端開發者",
    "React Developer",
    "Next.js Developer",
    "TypeScript Developer",
    "JavaScript Developer",
    "Python Developer",
    "React",
    "Next.js",
    "TypeScript",
    "JavaScript",
    "Python",
    "HTML 5",
    "CSS 3",
    "Tailwind CSS",
    "PostCSS",
    "CSS",
    "HTML",
    "GitHub",
    "Node.js",
    "Git",
    "API",
    "REST API",
    "RESTful API",
    "JSON",
    "Responsive Design",
    "Mobile First",
    "UI/UX",
    "UI/UX Design",
    "Web Performance",
    "SEO",
    "Software Engineer",
    "程式設計師",
    "軟體工程師",

    // 🛠️ 技術框架與工具
    "React 19",
    "Next.js 15",
    "TypeScript 5",
    "App Router",
    "Turbopack",
    "Framer Motion",
    "Ant Design",
    "React Icons",
    "styled-components",
    "clsx",
    "tailwind-merge",
    "SWR",
    "Giscus",
    "GitHub Discussions",
    "SweetAlert2",
    "Vercel",
    "Vercel Analytics",
    "Speed Insights",
    "Google Drive API",
    "Google APIs",
    "googleapis",
    "ESLint",
    "Visual Studio Code",
    "VS Code",
    "npm",
    "package manager",
    "Component Library",
    "fanyucomponents",
    "c063",
    "syntax highlighting",
    "程式碼高亮",
    "Slot Machine Game",
    "拉霸機遊戲",
    "Web Game",
    "網頁遊戲",

    // 🏫 教育背景
    "NTUST",
    "National Taiwan University of Science and Technology",
    "台科大",
    "臺灣科技大學",
    "國立臺灣科技大學",
    "治平高中",
    "CPSHS",
    "中和高中",
    "資訊管理系",
    "Information Management",
    "Department of Information Management",
    "電子商務科",
    "桌遊社",
    "桌上遊戲研究社",
    "台科大桌遊社",
    "NTUST桌遊社",
    "Board Game Club",
    "BoardGameClub",
    "美宣",
    "攝影",
    "富光國中",
    "福和國中",
    "永和國中",
    "FGJH",
    "關西國小",
    "GSES",
    "新竹縣",
    "關西",
    "關西鎮",
    "Guanxi Township",
    "Student Developer",
    "大學生開發者",

    // 🌍 地理位置 SEO
    "台灣開發者",
    "Taiwan Developer",
    "台北",
    "Taipei",
    "大安區",
    "Da'an District",
    "新竹",
    "Hsinchu",
    "新竹縣",
    "Hsinchu County",
    "台灣學生開發者",
    "Taiwan Student Developer",
    "中華民國",
    "Republic of China",
    "Taiwan",
    "臺灣",
    "Made in Taiwan",
    "Taiwan Tech",

    // 🧾 網站與用途 - 增加更多相關詞彙
    "personal website",
    "portfolio",
    "個人網站",
    "個人作品集",
    "開發作品",
    "履歷",
    "簡歷",
    "專案展示",
    "project showcase",
    "web portfolio",
    "developer portfolio",
    "student portfolio",
    "programming projects",
    "coding projects",
    "技術部落格",
    "tech blog",
    "fanyu.vercel.app",
    "Personal Portfolio Website",
    "多語言網站",
    "Multilingual Website",
    "中英文切換",
    "Language Switching",

    // 🎮 相關作品與彩蛋
    "LaBaG",
    "啦八機",
    "labag.vercel.app",
    "LabaG Web",
    "超級阿禾",
    "SuperHHH",
    "陳敬禾",
    "阿禾",
    "綠光阿瑋",
    "GreenWei",
    "拉霸機",
    "c063",
    "fanyucomponents",
    "fanyu-components",
    "Fanyu Components",
    "飯魚的組件",
    "小傲嬌",
    "Tools For Meta Information",
    "Meta 資訊處理工具",
    "meta-infomation-tools",
    "NTUST BoardGame Club Bot",
    "台科大桌遊社機器人",

    // 📚 專業領域長尾關鍵字
    "網頁前端開發",
    "React 專案",
    "Next.js 作品集",
    "TypeScript 開發",
    "響應式網頁設計",
    "現代網頁開發",
    "學生開發者作品",
    "開源專案",
    "GitHub 專案",
    "Web Development Taiwan",
    "Frontend Development Taiwan",
    "Modern Web Development",
    "JAMstack",
    "Static Site Generation",
    "Server Side Rendering",
    "SSR",
    "SSG",
    "PWA",
    "Progressive Web App",

    // 🎨 功能特色
    "相簿系統",
    "Album System",
    "Google Drive 相簿",
    "Google Drive Album",
    "動態相簿",
    "Dynamic Album",
    "留言板系統",
    "Guestbook System",
    "GitHub Discussions 留言板",
    "作品集篩選",
    "Portfolio Filtering",
    "多條件篩選",
    "Multi-filter",
    "動畫效果",
    "Animation Effects",
    "Framer Motion 動畫",
    "SEO 優化",
    "SEO Optimization",
    "網站分析",
    "Web Analytics",
    "性能優化",
    "Performance Optimization",
    "無障礙設計",
    "Accessibility",
    "結構化資料",
    "Structured Data",
    "JSON-LD",
    "Schema.org",
    "sitemap",
    "robots.txt",
    "Open Graph",
    "Twitter Card",
    "Meta Tags",
    
    // 🔧 開發技術
    "Component-Based Architecture",
    "組件化架構",
    "Hook-based Development",
    "Context API",
    "Custom Hooks",
    "TypeScript Interfaces",
    "API Routes",
    "Middleware",
    "Image Optimization",
    "圖片優化",
    "Code Splitting",
    "程式碼分割",
    "Bundle Optimization",
    "Tree Shaking",
    "Hot Reload",
    "Development Server",
    "Production Build",
    "Deployment",
    "CI/CD",
    "Version Control",
    "版本控制",
    "MIT License",
    "Open Source",
    "開源授權",

    // 🌐 社群媒體與聯絡方式
    "Instagram",
    "YouTube",
    "GitHub",
    "Discord",
    "Line",
    "Facebook",
    "Messenger",
    "Gmail",
    "Threads",
    "TikTok",
    "Bilibili",
    "WakaTime",
    "Retro",
    "Social Media",
    "社群媒體",
    "Contact Information",
    "聯絡方式",
    "Social Network",
    "Instant Messaging",
    "即時通訊",
  ];